# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-JugemKey-Auth
version:      0.04
version_from: lib/WebService/JugemKey/Auth.pm
installdirs:  site
requires:
    DateTime:                      0
    DateTime::Format::W3CDTF:      0
    Digest::HMAC:                  0
    Digest::SHA1:                  0
    LWP::UserAgent:                0
    Test::More:                    0
    URI:                           0
    XML::Atom::Entry;:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
